version: "3.1"

services:
  mysql:
    container_name: mysql_picpay_challenge
    hostname: mysql_picpay_challenge
    image: mysql
    restart: always
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --innodb_force_recovery=0
    volumes:
      - ./local/path:/container/path
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: picpay_challenge
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: America/Sao_Paulo